---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 24h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  values:
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 10Gi
        jobservice:
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 5Gi
        database:
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 5Gi
        redis:
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 5Gi
        trivy:
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 5Gi
    externalURL: https://harbor.nieradko.com
    expose:
      tls:
        secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.nieradko.com
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
        tag: v2.12.0
    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
        tag: v2.12.0
    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
        tag: v2.12.0
    registry:
      registry:
        image:
          repository: ghcr.io/octohelm/harbor/registry-photon
          tag: v2.12.0
      controller:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-registryctl
          tag: v2.12.0
    trivy:
      image:
        repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
        tag: v2.12.0
    database:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-db
          tag: v2.12.0
    redis:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/redis-photon
          tag: v2.12.0
    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter
        tag: v2.12.0
